# Generated by Django 3.2.4 on 2021-06-27 02:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('any_lease', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Users',
            new_name='Customer',
        ),
    ]
