# Generated by Django 3.2.4 on 2021-06-29 01:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20210629_0112'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='e_mail',
            field=models.EmailField(max_length=254),
        ),
    ]
