# Generated by Django 3.2.4 on 2021-07-06 01:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_remove_customer_middle_name'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Customer',
        ),
    ]
